### ISSUE TITLE
MicroPython v1.16: uasyncio incomplete

### ISSUE THREAD

**Issue by JeffreyUrban** [JeffreyUrban/MaixPy#4]
**Describe the bug**
The uasyncio module appears present as _uasyncio, but is missing most features.

**To Reproduce**

Build and flash with branch update-mp-v1.16 commit [f0897da](https://github.com/JeffreyUrban/MaixPy/commit/f0897da1734cda46a316ea58c21231a7c9f47e08).
Boot, run commands as follows.

**Expected behavior**

(As tested on ESP32 MicroPython v1.18)

Can import uasyncio:
```
>>> import uasyncio
>>>
```

Can create an async def function:
```
>>> async def hello():
...
```

Tab completion shows many more components (may be less in v1.16):
```
>>> uasyncio.
CancelledError  Task            TaskQueue       lock
run             select          sleep           sleep_ms
sys             ticks_add       ticks_diff      core
__version__     funcs           wait_for        gather
event           Event           Lock            stream
_attrs          ticks           TimeoutError
SingletonGenerator              IOQueue         create_task
run_until_complete              Loop            get_event_loop
current_task    new_event_loop  ThreadSafeFlag  wait_for_ms
StreamReader    StreamWriter    open_connection
start_server
```

**Actual behaviour**

Cannot import uasyncio:
```
>>>import uasyncio
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: no module named 'uasyncio'
```

Cannot create an async def function:
```
>>> import _uasyncio
>>> async def hello():
Traceback (most recent call last):
  File "<stdin>", line 1
SyntaxError: invalid syntax
```

Tab completion shows only components Task, TaskQueue:
```
>>> _uasyncio.Task
Task            TaskQueue
```

**Screenshots**
N/A

**Please complete the following information**
 - IDE version: N/A
 - Firmware version: Firmware version: Based on sipeed/MaixPy 22a8555, merged into JishinMaster/MaixPy 7fea043, modified for MicroPython v1.16.
 - Board: Maix Bit with mic
 - OS: Mac OS Monterey

**Comment by JeffreyUrban** [comment]
_uasyncio is a helper module for the real uasyncio package, which is why it appears to have only part of the functionality. 

uasyncio uses the [MicroPython manifest mechanism](https://docs.micropython.org/en/latest/reference/manifest.html), which is new since MaixPy was implemented. It is not clear how to include a manifest.py file within the MaixPy build, or otherwise reference a package like uasyncio using the MaixPy builtin_py directory and existing mechanism. My attempts to do so have been unsuccessful.
